### ISSUE TITLE
How can I calculate q-prior on my dataset?

### ISSUE THREAD

**Issue by jinok2im** [Time0o/colorful-colorization#39]
Thanks very much for sharing the code for this work!

I have a question here:

I'd like to calculate q-prior on my dataset instead of image-net.
So, I obtained empirical distribution using plot_empirical_distribution first.
But I'm not sure how to quantize this ab_acc_log value to get my q-prior.npy file.
Could you briefly explain how to do this?

Hope to hear from you, thanks!

**Comment by jinok2im** [comment]
I got 23x23 ab_acc_log grid using 10x10 average-pooling operation with no-overlap and then applied ab_gamut_mask.
Is this the same method used in the paper?

**Comment by Time0o** [comment]
That's a good question. I'm not sure if I've actually tried doing this for a separate dataset myself and it's been a while. I will look into it and get back to you.

**Comment by jinok2im** [comment]
Thank you for quick response.

I checked my `q` is a probability distribution as you mentioned.
In my case, there are some '0' probability point in the distribution.
So, I added eps to compute weights as below. (Since 1 / 0 = Inf.)

Is it logically the right approach?

```
class GetClassWeights:
    def __init__(self, cielab, lambda_=0.5, device='cuda'):
        eps = 1e-7
        prior = torch.from_numpy(cielab.gamut.prior).to(device)

        uniform = torch.zeros_like(prior)
        uniform[prior > 0] = 1 / (prior > 0).sum().type_as(uniform)

        self.weights = 1 / ((1 - lambda_) * prior + lambda_ * uniform + eps)
        self.weights /= torch.sum(prior * self.weights)
```

**Comment by Time0o** [comment]
Sorry for not replying sooner, here's what I have tried out: I first modifier the `Cielab.bin_ab function` as follows:

```python
def bin_ab(self, ab, hist=False):
    ab_discrete = ((ab + 110) / self.AB_RANGE[2]).astype(int)

    a, b = np.hsplit(ab_discrete.reshape(-1, 2), 2)

    q = self.ab_to_q[a, b].reshape(*ab.shape[:2])

    if not hist:
         return q

    q_hist = np.zeros(313, dtype=self.Q_DTYPE)

    np.add.at(q_hist, q, 1)

    return q_hist
```

When `hist` is`True`, the returned array then has the correct shape `(313,)` and is essentially a histogram of the AB bins in which the input images pixels fall. Example:

```python
from colorization import CIELAB
from colorization.util.image import imread, rgb_to_lab

img = imread(...)
img_ab = rbg_to_lab(img)[:,:,1:]

cl = CIELAB()
q = cl.bin_ab(img_ab, hist=True)
```
You can then load a bunch of images, calculate `q` for each of them, sum the results together and transform the result into a probability distribution (here I am not sure if you have to take the logarithm at the end or something, I would suggest trying it out with an ImageNet subset and comparing the result to the provided prior).

Then just set `CIELAB.prior` to your calculated prior and everything should work. It is possible that this is equivalent to what you've already tried but I'm not sure.

It would maybe be nice to have a script under `scripts/` that does all of this a set of images and creates a new `.npy` prior file. Since people still seem to be interested in this repository you could create a pull request for that if you have extra time.

**Comment by jinok2im** [comment]
Thank you for the detailed answer.

It's a good idea to write a script that executes the whole process to create a new `.npy` prior file.

I will try and leave a comment or create a pull request for that.

**Comment by IricsDo** [comment]
Hi guys, i meet the problem when load pts_in_hull .npy and prior_probs.npy file. What version numpy do you use? 
The error like : **ValueError: Cannot load file containing pickled data when allow_pickle=False**
If i change allow_pickle=True, it have another error like: 
EOFError: Ran out of input, During handling of the above exception, another exception occurred: 
OSError: Failed to interpret file .... ./resources/ab-gamut.npy' as a pickle
Pls help me slove this, thanks all

**Comment by Time0o** [comment]
@IricsDo That's because the files downloaded by `get_resources.sh` were outdated, I've changed the script in 7a9bd391e3b2856f45ad7699457dc4ee1bdbd20d to download more recent ones which should work with numpy again (I've tested it with numpy `1.20.1`).

**Comment by IricsDo** [comment]
Thanks guys. This was slove
